language: csharp
dotnet: 2.0.0
script:
   - cd SimpleMapper.Test
   # once test command runs on the above proj, that proj forces build of the main proj since it holds reference to it.
   # there is no need to reference the whole solution
   - dotnet test
   # dotnet test runs: dotnet restore and dotnet build before running tests
