language: csharp
solution: SimpleMapper.sln
install:
  - nuget restore SimpleMapper.sln
  - nuget install NUnit.Runners -Version 3.10.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SimpleMapper.sln
  - mono ./testrunner/NUnit.Runners.3.10.1/tools/nunit-console.exe ./SimpleMapper.Test/bin/Release/SimpleMapper.Test.dll
